### ISSUE TITLE
A more responsive UI for the devtools view

### ISSUE THREAD

**Issue by AtlasWiki** [AtlasWiki/EndPointer#26]
Currently, listing the URLs in the devtools UI needs work on responsiveness. Users would have to zoom out or significantly enlarge the developer tools to visibly see the URLs. The goal is to have users view all URLs and the table without having to have such a long developer tools window size taking up almost the whole screen.

**Comment by mahenoorsalat** [comment]
I want to work on this issue .. assign me this 

Thank you :)


> Currently, listing the URLs in the devtools UI needs work on responsiveness. Users would have to zoom out or significantly enlarge the developer tools to visibly see the URLs. The goal is to have users view all URLs and the table without having to have such a long developer tools window size taking up almost the whole screen.

**Comment by AtlasWiki** [comment]
> I want to work on this issue .. assign me this
> 
> Thank you :)
> 
> > Currently, listing the URLs in the devtools UI needs work on responsiveness. Users would have to zoom out or significantly enlarge the developer tools to visibly see the URLs. The goal is to have users view all URLs and the table without having to have such a long developer tools window size taking up almost the whole screen.

Assigned! Thank you!

**Comment by AtlasWiki** [comment]
The PR has been reviewed and accepted for issue #26! This count towards issue #26 for creating a new UI design. This issue is a separate issue from issue #27 as the PR focused on the popup UI. See the image below for the developer tools UI (found with opening inspect element). This current issue relates to the responsiveness of the devtools UI. The current issue is about how the developer tools window is too big and takes up most of the webpage. Thank you for your active contribution and time :)! 

![image](https://github.com/user-attachments/assets/8ac82f1b-0d27-4e0b-ba6b-521a6ebbe1f8)
