### ISSUE TITLE
UI design alternatives (devtools, popup, webpage)

### ISSUE THREAD

**Issue by AtlasWiki** [AtlasWiki/EndPointer#27]
Currently the UI design is simple and user-friendly providing a reasonable UX for the users, but however we are opened in accepting any new UI designs and reworks or even subtle changes to the UI.

**Comment by mahenoorsalat** [comment]
I want to work on this issue

assign me this :)

**Comment by AtlasWiki** [comment]
> I want to work on this issue
> 
> assign me this :)

Assigned!
