### ISSUE TITLE
URL Classification Functionality (UI design & Logic)

### ISSUE THREAD

**Issue by AtlasWiki** [AtlasWiki/EndPointer#28]
Together we will work on adding tags/categories associated with the URL. For example, the URL "/admin-dashboard/edit-users" would be classified as an "admin" endpoint or "admin privileges." Another example is "/email/inbox" this may be classified as "User Data Access" as this endpoint is associated to basic user level privileges. 

Now for the UI, we would need to display visual tags, add a sort button, and a filter button to filter/sort these URL classification/categories.

**Comment by rohitja26** [comment]
@AtlasWiki  assign this to me and please provide the deployed link as well as clear the requirement

**Comment by AtlasWiki** [comment]
@rohitja26 Hi, im sorry to say this was a misunderstanding and that it's my first time participating in hacktober. I realized this is no small task as it would change how the parser works and the system of it which could also lead to refactoring and a lot of changes taking some time to complete. Sorry for taking up your time, but before any more is wasted, I hereby close this issue. If you wish to help this project still, you can go to the other issues or create new ones. If you are willing to spend some time to work on this issue and even have us work with you on this, then please contact my discord username .mrunoriginal and we can talk about it, and potentially reopen this issue depending on the situation.

**Comment by rohitja26** [comment]
@AtlasWiki  fine
