### ISSUE TITLE
Small tweaks to popup UI

### ISSUE THREAD

**Issue by AtlasWiki** [AtlasWiki/EndPointer#39]
Currently, the popup UI is going through changes, but there are minor tweaks and fixes or enhancements that are welcomed for changes. For example, the logo is a little small and not aligned with the EndPointer title. The text on the buttons could use some color changes, typography, and more. Any changes/design is allowed as long as it provides a great UX experience for users.

**Comment by mahenoorsalat** [comment]
I will look into this issue .. Assign it to me 

Thank you :) @AtlasWiki

**Comment by AtlasWiki** [comment]
Thank you! Assigned.
