### ISSUE TITLE
UI design for DevTools Dashboard (& URLs list?) (DevToolsApp.tsx)

### ISSUE THREAD

**Issue by AtlasWiki** [AtlasWiki/EndPointer#41]
![image](https://github.com/user-attachments/assets/e6641148-24da-4e3a-994e-68dabe09fe44)

![image](https://github.com/user-attachments/assets/8e33bc0d-3053-49fc-b85b-b22e96841467)

Currently, these are the designs for the dashboard in developer tools as well as the URLs list for them.

**Comment by mahenoorsalat** [comment]
will look into this .. assign me :)

**Comment by AtlasWiki** [comment]
Thank you for your contribution again! You have been assigned and we appreciate all your support! Due to your contributions and hard work ethic, we will add you to our hall of fame :)!

**Comment by mahenoorsalat** [comment]
wonderful  ! Thank you :)
