### ISSUE TITLE
Redesign of parsing state on the current document (editing urlparser.ts aka the content script)

### ISSUE THREAD

**Issue by AtlasWiki** [AtlasWiki/EndPointer#42]
While the Auto Parser is on, it parses the webpage when you refresh the page, causing a loading/progress bar to display while it's parsing. Any enhancement or modification that provides users a better UX is acceptable. This can be found in src/content/urlParser.ts

**Comment by mahenoorsalat** [comment]
I will look into this matter .. assign me :)

**Comment by AtlasWiki** [comment]
Thank you for yet another contribution!!! you have been assigned, and we won't forget your contribution and recognition :)
